version: '3.8'

services:
  db:
    image: mysql:8.0.2
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: expensesdb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  # Backend Spring Boot
  api:
    build:
      context: ./ExpenseDashboard
      dockerfile: Dockerfile
    container_name: spring_api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/expensesdb?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
      API_SECURITY_TOKEN_SECRETKEY: super-secret-key
    depends_on:
      - db
    networks:
      - app-network

  # Frontend Angular
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: angular_app
    ports:
      - "4200:4200"
    depends_on:
      - api
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
